version: '3.9'

services:
  mysql:
    container_name: mysql_node_rest
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_DATABASE: "${MYSQL_DBNAME}"